import { AnimatePresence, motion, useReducedMotion } from "motion/react"
import type { DemoFrame } from "../lib/mockData"
import { useDashboardStore } from "../state/store"
import type { RealSceneStatus } from "./RealScene"

function MetricRow({ label, value, note, emphasis = false }: { label: string; value: string; note: string; emphasis?: boolean }) {
  return (
    <div className="rounded-lg border border-white/[0.08] bg-white/[0.025] p-3">
      <div className="flex items-baseline justify-between gap-3">
        <span className="text-xs font-medium text-slate-200">{label}</span>
        <span className={`font-mono-tech text-sm tabular-nums ${emphasis ? "text-cyan-100" : "text-slate-300"}`}>{value}</span>
      </div>
      <p className="mt-1 text-[11px] leading-4 text-slate-500">{note}</p>
    </div>
  )
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return <h3 className="mt-5 mb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-cyan-300/85 first:mt-0">{children}</h3>
}

function toMb(cellCount: number): string {
  return `${((cellCount * 5 * 4) / (1024 * 1024)).toFixed(2)} MB`
}

export function EvidenceDrawer({ demoFrame, realStatus, realDataMode }: { demoFrame: DemoFrame; realStatus: RealSceneStatus | null; realDataMode: boolean }) {
  const evidenceOpen = useDashboardStore((s) => s.evidenceOpen)
  const setEvidenceOpen = useDashboardStore((s) => s.setEvidenceOpen)
  const reducedMotion = useReducedMotion()

  const uniformMb = 201.3
  const foveatedMb = demoFrame.hud.mbUsed
  const reduction = uniformMb / foveatedMb
  const serialisedCells = realStatus ? (realStatus.useAccumulated ? realStatus.frame.accumulatedCellCount : realStatus.frame.cellCount) : 0

  return (
    <AnimatePresence>
      {evidenceOpen && (
        <motion.aside
          role="dialog"
          aria-modal="true"
          aria-labelledby="evidence-title"
          className="fixed inset-y-0 right-0 z-50 flex w-full max-w-[26rem] flex-col border-l border-white/10 bg-[#0a111d]/98 shadow-2xl backdrop-blur-xl"
          initial={reducedMotion ? { opacity: 0 } : { opacity: 0, x: 36 }}
          animate={{ opacity: 1, x: 0 }}
          exit={reducedMotion ? { opacity: 0 } : { opacity: 0, x: 36 }}
          transition={{ duration: reducedMotion ? 0.01 : 0.22, ease: [0.22, 1, 0.36, 1] }}
        >
          <div className="flex items-start justify-between border-b border-white/10 px-5 py-4">
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-cyan-300/85">Measured context</p>
              <h2 id="evidence-title" className="mt-1 text-base font-semibold text-slate-100">Evidence and provenance</h2>
            </div>
            <button
              type="button"
              onClick={() => setEvidenceOpen(false)}
              className="flex h-11 w-11 items-center justify-center rounded-lg border border-white/10 text-slate-300 transition-colors hover:bg-white/[0.07] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-300"
              aria-label="Close evidence panel"
            >
              <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true">
                <path d="m6 6 12 12M18 6 6 18" />
              </svg>
            </button>
          </div>

          <div className="min-h-0 flex-1 overflow-y-auto px-5 py-4">
            <SectionTitle>Memory comparison</SectionTitle>
            <div className="space-y-2">
              <MetricRow label="Uniform 5 cm baseline" value={`${uniformMb.toFixed(1)} MB`} note="Synthetic demonstration baseline across the same mapped extent." />
              <MetricRow label="Foveated clipmap" value={`${foveatedMb.toFixed(2)} MB`} note={`Synthetic demonstration frame; ${reduction.toFixed(1)}× smaller than the uniform baseline.`} emphasis />
            </div>

            <SectionTitle>Current source</SectionTitle>
            {realDataMode && realStatus ? (
              <div className="space-y-2">
                <MetricRow label="Run" value={`${realStatus.manifest.nFrames} frames`} note={`${realStatus.manifest.sequenceDir}; checkpoint epoch ${realStatus.manifest.trainedEpoch}.`} />
                <MetricRow
                  label="Cell payload"
                  value={toMb(serialisedCells)}
                  note={`${serialisedCells.toLocaleString()} visible cell records × 5 float32 values. This is serialized payload size, not a runtime-memory claim.`}
                />
              </div>
            ) : (
              <MetricRow label="Active source" value="Synthetic" note="The displayed planning, speed, and latency values are generated by the frontend scenario." />
            )}

            <SectionTitle>Resolution schedule</SectionTitle>
            <div className="space-y-2">
              {(realStatus?.manifest.levels ?? []).map((level) => (
                <MetricRow
                  key={level.level}
                  label={`Level ${level.level}`}
                  value={`${(level.cellSizeM * 100).toFixed(0)} cm`}
                  note={`Applies through ${level.nyquistRadiusM.toFixed(1)} m from the sensor in this export.`}
                />
              ))}
              {!realStatus && <MetricRow label="Live fovea" value="Adaptive" note="The synthetic view exposes a client-side gamma control for foveated sampling." />}
            </div>

            <SectionTitle>Metrics not present in this export</SectionTitle>
            <div className="rounded-lg border border-dashed border-white/15 bg-white/[0.02] p-3">
              <p className="text-xs font-medium text-slate-300">Accuracy-by-distance and end-to-end latency</p>
              <p className="mt-1 text-[11px] leading-4 text-slate-500">No static evaluation artifact is served by the frontend, so these measurements are deliberately not fabricated here.</p>
            </div>
          </div>
        </motion.aside>
      )}
    </AnimatePresence>
  )
}
